services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:17
    container_name: geomap_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: