services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: geomap_backend_dev
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/uploads:/root/uploads
      - ./backend:/app/backend
    restart: always

  db:
    image: postgis/postgis:17-3.4
    container_name: geomap_db_dev
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev:
